[package]
name = "scryfall-api"
version = "0.1.0"
authors = ["Chris Schneider <chris@scoutapp.com>"]

[dependencies]
chrono = { version = "*", features = ["serde"] }
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
url = "*"

